# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\x05greet\"%\n\rInputPosition\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01z\x18\x02 \x01(\x02\"\"\n\x08OutputAI\x12\n\n\x02\x66x\x18\x01 \x01(\x02\x12\n\n\x02\x66z\x18\x02 \x01(\x02\x32\x46\n\x07Greeter\x12;\n\x12RequestInstruction\x12\x14.greet.InputPosition\x1a\x0f.greet.OutputAIB\x0e\xaa\x02\x0bGrpcGreeterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\013GrpcGreeter'
  _globals['_INPUTPOSITION']._serialized_start=27
  _globals['_INPUTPOSITION']._serialized_end=64
  _globals['_OUTPUTAI']._serialized_start=66
  _globals['_OUTPUTAI']._serialized_end=100
  _globals['_GREETER']._serialized_start=102
  _globals['_GREETER']._serialized_end=172
# @@protoc_insertion_point(module_scope)
